version: '3.8'
services: 

  nginx-gateway:
    image: nginx:latest
    container_name: nginx_gateway
    depends_on: 
      - account-service-1
      - account-service-2
      - account-service-3
      - forum-service-1
      - forum-service-2
      - forum-service-3
      - homepage-service-1
      - homepage-service-2
      - homepage-service-3
      - db
      - react
      - predictions-service
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    
  react:
    container_name: react-client
    build: 
      context: .
      dockerfile: Dockerfile.dockerfile
    ports:
      - 5000:5000
    
  db:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=MarLee21!
      - MYSQL_PASSWORD=MarLee21!
      - MYSQL_USER=Marcus
      - MYSQL_DATABASE=data
    expose: 
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  account-service-1:
    container_name: account-service-1
    build: 
      context: .
      dockerfile: ./src/docker/account/Dockerfile.dockerfile
    expose:
      - 80
    depends_on: 
      - db
  
  account-service-2:
    container_name: account-service-2
    build: 
      context: .
      dockerfile: ./src/docker/account/Dockerfile.dockerfile
    expose:
      - 80
    depends_on: 
      - db

  account-service-3:
    container_name: account-service-3
    build: 
      context: .
      dockerfile: ./src/docker/account/Dockerfile.dockerfile
    expose:
      - 80
    depends_on: 
      - db
  
  forum-service-1:
    container_name: forum-service-1
    build:
      context: .
      dockerfile: ./src/docker/forum/Dockerfile.dockerfile
    expose: 
      - 80
    depends_on: 
      - db
  
  forum-service-2:
    container_name: forum-service-2
    build:
      context: .
      dockerfile: ./src/docker/forum/Dockerfile.dockerfile
    expose: 
      - 80
    depends_on: 
      - db

  forum-service-3:
    container_name: forum-service-3
    build:
      context: .
      dockerfile: ./src/docker/forum/Dockerfile.dockerfile
    expose: 
      - 80
    depends_on: 
      - db

  homepage-service-1:
    container_name: homepage-service-1
    build:
      context: .
      dockerfile: ./src/docker/homepage/Dockerfile.dockerfile
    expose: 
      - 80
    depends_on: 
      - db

  homepage-service-2:
    container_name: homepage-service-2
    build:
      context: .
      dockerfile: ./src/docker/homepage/Dockerfile.dockerfile
    expose: 
      - 80
    depends_on: 
      - db

    homepage-service-3:
    container_name: homepage-service-3
    build:
      context: .
      dockerfile: ./src/docker/homepage/Dockerfile.dockerfile
    expose: 
      - 80
    depends_on: 
      - db
  
  predictions-service:
    container_name: predictions-service
    build:
      context: .
      dockerfile: ./src/docker/predictions/Dockerfile.dockerfile
    expose:
      - 80
    depends_on: 
      - db

volumes:
  mysql-data: