version: '3.8'
services: 

  nginx-gateway:
    image: nginx:latest
    container_name: nginx_gateway
    depends_on: 
      - account-service
      - forum-service
      - homepage-service
      - db
      - react
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  react:
    container_name: react-client
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    ports:
      - 5000:5000
    
  db:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=MarLee21!
      - MYSQL_PASSWORD=MarLee21!
      - MYSQL_USER=Marcus
      - MYSQL_DATABASE=data
    expose: 
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  account-service:
    container_name: account-service
    build: 
      context: .
      dockerfile: ./src/docker/account/Dockerfile.dockerfile
    #volumes:
      #- ./src/resources:/code
      #- ./src/account:/code/account
    #ports:
    #  - 5002:5002
    expose:
      - 80
    depends_on: 
      - db
  
  forum-service:
    container_name: forum-service
    build:
      context: .
      dockerfile: ./src/docker/forum/Dockerfile.dockerfile
    #volumes:
      #- ./src/resources:/code
      #- ./src/forum:/code/forum
    #ports:
    #  - 5003:5003
    expose: 
      - 80
    depends_on: 
      - db

  homepage-service:
    container_name: homepage-service
    build:
      context: .
      dockerfile: ./src/docker/homepage/Dockerfile.dockerfile
    #volumes:
      #- ./src/resources:/code
      #- ./src/homepage:/code/homepage
    #ports:
    #  - 5004:5004
    expose: 
      - 80

volumes:
  mysql-data: